# Generated by Django 5.0.1 on 2026-02-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Epreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "caracteristique",
                    models.CharField(
                        choices=[
                            ("INDIV", "Individuel"),
                            ("EQUIPE", "Par Équipe"),
                            ("MIXTE", "Les deux"),
                        ],
                        default="INDIV",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Compétition Départementale 2024", max_length=200
                    ),
                ),
                (
                    "epreuves",
                    models.ManyToManyField(
                        related_name="competitions", to="core.epreuve"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="epreuve",
            name="sport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="epreuves",
                to="core.sport",
            ),
        ),
        migrations.CreateModel(
            name="Championnat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Championnat National Athlétisme", max_length=200
                    ),
                ),
                (
                    "competitions",
                    models.ManyToManyField(
                        related_name="championnats", to="core.competition"
                    ),
                ),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.sport"
                    ),
                ),
            ],
        ),
    ]
